; (quaternary x)
; function that converts a positive integer in base 10 to the quaternary numeral system (base 4)

(define (quaternary n)
  (define (getLength n acc)
    ( if( >= n (expt 4 acc))
        (getLength n (+ acc 1))
        (- acc 1)
    )
  )
  (define (getNum n acc)
    ( cond ((< (/ n (expt 4 acc)) 1) '0)
           ((< (/ n (expt 4 acc)) 2) '1)
           ((< (/ n (expt 4 acc)) 3) '2)
           ((< (/ n (expt 4 acc)) 4) '3)
           )
    )
  (define (calculate n acc)
    (if (= acc 0)
        (list (getNum n acc))
        (append (list (getNum n acc)) (calculate (modulo n (expt 4 acc)) (- acc 1)))   
        )
    )

  (calculate n (getLength n 0) )
)
